// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_CHAT;
struct C_CHATDefaultTypeInternal;
extern C_CHATDefaultTypeInternal _C_CHAT_default_instance_;
class C_LOGIN;
struct C_LOGINDefaultTypeInternal;
extern C_LOGINDefaultTypeInternal _C_LOGIN_default_instance_;
class C_PLAYER_INPUT;
struct C_PLAYER_INPUTDefaultTypeInternal;
extern C_PLAYER_INPUTDefaultTypeInternal _C_PLAYER_INPUT_default_instance_;
class S_CHAT;
struct S_CHATDefaultTypeInternal;
extern S_CHATDefaultTypeInternal _S_CHAT_default_instance_;
class S_LOGIN;
struct S_LOGINDefaultTypeInternal;
extern S_LOGINDefaultTypeInternal _S_LOGIN_default_instance_;
class S_MONSTER_DESPAWN;
struct S_MONSTER_DESPAWNDefaultTypeInternal;
extern S_MONSTER_DESPAWNDefaultTypeInternal _S_MONSTER_DESPAWN_default_instance_;
class S_MONSTER_MOVE;
struct S_MONSTER_MOVEDefaultTypeInternal;
extern S_MONSTER_MOVEDefaultTypeInternal _S_MONSTER_MOVE_default_instance_;
class S_MONSTER_SPAWN;
struct S_MONSTER_SPAWNDefaultTypeInternal;
extern S_MONSTER_SPAWNDefaultTypeInternal _S_MONSTER_SPAWN_default_instance_;
class S_PLAYER_ENTER;
struct S_PLAYER_ENTERDefaultTypeInternal;
extern S_PLAYER_ENTERDefaultTypeInternal _S_PLAYER_ENTER_default_instance_;
class S_PLAYER_EXIT;
struct S_PLAYER_EXITDefaultTypeInternal;
extern S_PLAYER_EXITDefaultTypeInternal _S_PLAYER_EXIT_default_instance_;
class S_PLAYER_MOVE;
struct S_PLAYER_MOVEDefaultTypeInternal;
extern S_PLAYER_MOVEDefaultTypeInternal _S_PLAYER_MOVE_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_CHAT* Arena::CreateMaybeMessage<::Protocol::C_CHAT>(Arena*);
template<> ::Protocol::C_LOGIN* Arena::CreateMaybeMessage<::Protocol::C_LOGIN>(Arena*);
template<> ::Protocol::C_PLAYER_INPUT* Arena::CreateMaybeMessage<::Protocol::C_PLAYER_INPUT>(Arena*);
template<> ::Protocol::S_CHAT* Arena::CreateMaybeMessage<::Protocol::S_CHAT>(Arena*);
template<> ::Protocol::S_LOGIN* Arena::CreateMaybeMessage<::Protocol::S_LOGIN>(Arena*);
template<> ::Protocol::S_MONSTER_DESPAWN* Arena::CreateMaybeMessage<::Protocol::S_MONSTER_DESPAWN>(Arena*);
template<> ::Protocol::S_MONSTER_MOVE* Arena::CreateMaybeMessage<::Protocol::S_MONSTER_MOVE>(Arena*);
template<> ::Protocol::S_MONSTER_SPAWN* Arena::CreateMaybeMessage<::Protocol::S_MONSTER_SPAWN>(Arena*);
template<> ::Protocol::S_PLAYER_ENTER* Arena::CreateMaybeMessage<::Protocol::S_PLAYER_ENTER>(Arena*);
template<> ::Protocol::S_PLAYER_EXIT* Arena::CreateMaybeMessage<::Protocol::S_PLAYER_EXIT>(Arena*);
template<> ::Protocol::S_PLAYER_MOVE* Arena::CreateMaybeMessage<::Protocol::S_PLAYER_MOVE>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_LOGIN) */ {
 public:
  inline C_LOGIN() : C_LOGIN(nullptr) {}
  ~C_LOGIN() override;
  explicit constexpr C_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_LOGIN(const C_LOGIN& from);
  C_LOGIN(C_LOGIN&& from) noexcept
    : C_LOGIN() {
    *this = ::std::move(from);
  }

  inline C_LOGIN& operator=(const C_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LOGIN& operator=(C_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_LOGIN* internal_default_instance() {
    return reinterpret_cast<const C_LOGIN*>(
               &_C_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_LOGIN& a, C_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(C_LOGIN* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_LOGIN* New() const final {
    return new C_LOGIN();
  }

  C_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_LOGIN>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_LOGIN& from);
  void MergeFrom(const C_LOGIN& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_LOGIN* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_LOGIN";
  }
  protected:
  explicit C_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_LOGIN) */ {
 public:
  inline S_LOGIN() : S_LOGIN(nullptr) {}
  ~S_LOGIN() override;
  explicit constexpr S_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_LOGIN(const S_LOGIN& from);
  S_LOGIN(S_LOGIN&& from) noexcept
    : S_LOGIN() {
    *this = ::std::move(from);
  }

  inline S_LOGIN& operator=(const S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LOGIN& operator=(S_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_LOGIN* internal_default_instance() {
    return reinterpret_cast<const S_LOGIN*>(
               &_S_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_LOGIN& a, S_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(S_LOGIN* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_LOGIN* New() const final {
    return new S_LOGIN();
  }

  S_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_LOGIN>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_LOGIN& from);
  void MergeFrom(const S_LOGIN& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_LOGIN* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_LOGIN";
  }
  protected:
  explicit S_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOtherPlayersFieldNumber = 3,
    kMyPlayerFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // repeated .Protocol.Player otherPlayers = 3;
  int otherplayers_size() const;
  private:
  int _internal_otherplayers_size() const;
  public:
  void clear_otherplayers();
  ::Protocol::Player* mutable_otherplayers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
      mutable_otherplayers();
  private:
  const ::Protocol::Player& _internal_otherplayers(int index) const;
  ::Protocol::Player* _internal_add_otherplayers();
  public:
  const ::Protocol::Player& otherplayers(int index) const;
  ::Protocol::Player* add_otherplayers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
      otherplayers() const;

  // .Protocol.Player myPlayer = 2;
  bool has_myplayer() const;
  private:
  bool _internal_has_myplayer() const;
  public:
  void clear_myplayer();
  const ::Protocol::Player& myplayer() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::Protocol::Player* release_myplayer();
  ::Protocol::Player* mutable_myplayer();
  void set_allocated_myplayer(::Protocol::Player* myplayer);
  private:
  const ::Protocol::Player& _internal_myplayer() const;
  ::Protocol::Player* _internal_mutable_myplayer();
  public:
  void unsafe_arena_set_allocated_myplayer(
      ::Protocol::Player* myplayer);
  ::Protocol::Player* unsafe_arena_release_myplayer();

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player > otherplayers_;
  ::Protocol::Player* myplayer_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PLAYER_ENTER final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PLAYER_ENTER) */ {
 public:
  inline S_PLAYER_ENTER() : S_PLAYER_ENTER(nullptr) {}
  ~S_PLAYER_ENTER() override;
  explicit constexpr S_PLAYER_ENTER(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PLAYER_ENTER(const S_PLAYER_ENTER& from);
  S_PLAYER_ENTER(S_PLAYER_ENTER&& from) noexcept
    : S_PLAYER_ENTER() {
    *this = ::std::move(from);
  }

  inline S_PLAYER_ENTER& operator=(const S_PLAYER_ENTER& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PLAYER_ENTER& operator=(S_PLAYER_ENTER&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PLAYER_ENTER& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PLAYER_ENTER* internal_default_instance() {
    return reinterpret_cast<const S_PLAYER_ENTER*>(
               &_S_PLAYER_ENTER_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S_PLAYER_ENTER& a, S_PLAYER_ENTER& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PLAYER_ENTER* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PLAYER_ENTER* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_PLAYER_ENTER* New() const final {
    return new S_PLAYER_ENTER();
  }

  S_PLAYER_ENTER* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_PLAYER_ENTER>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_PLAYER_ENTER& from);
  void MergeFrom(const S_PLAYER_ENTER& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PLAYER_ENTER* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PLAYER_ENTER";
  }
  protected:
  explicit S_PLAYER_ENTER(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 1,
  };
  // repeated .Protocol.Player players = 1;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::Protocol::Player* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
      mutable_players();
  private:
  const ::Protocol::Player& _internal_players(int index) const;
  ::Protocol::Player* _internal_add_players();
  public:
  const ::Protocol::Player& players(int index) const;
  ::Protocol::Player* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
      players() const;

  // @@protoc_insertion_point(class_scope:Protocol.S_PLAYER_ENTER)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player > players_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PLAYER_EXIT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PLAYER_EXIT) */ {
 public:
  inline S_PLAYER_EXIT() : S_PLAYER_EXIT(nullptr) {}
  ~S_PLAYER_EXIT() override;
  explicit constexpr S_PLAYER_EXIT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PLAYER_EXIT(const S_PLAYER_EXIT& from);
  S_PLAYER_EXIT(S_PLAYER_EXIT&& from) noexcept
    : S_PLAYER_EXIT() {
    *this = ::std::move(from);
  }

  inline S_PLAYER_EXIT& operator=(const S_PLAYER_EXIT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PLAYER_EXIT& operator=(S_PLAYER_EXIT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PLAYER_EXIT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PLAYER_EXIT* internal_default_instance() {
    return reinterpret_cast<const S_PLAYER_EXIT*>(
               &_S_PLAYER_EXIT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S_PLAYER_EXIT& a, S_PLAYER_EXIT& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PLAYER_EXIT* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PLAYER_EXIT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_PLAYER_EXIT* New() const final {
    return new S_PLAYER_EXIT();
  }

  S_PLAYER_EXIT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_PLAYER_EXIT>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_PLAYER_EXIT& from);
  void MergeFrom(const S_PLAYER_EXIT& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PLAYER_EXIT* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PLAYER_EXIT";
  }
  protected:
  explicit S_PLAYER_EXIT(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdsFieldNumber = 1,
  };
  // repeated uint64 playerIds = 1;
  int playerids_size() const;
  private:
  int _internal_playerids_size() const;
  public:
  void clear_playerids();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_playerids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_playerids() const;
  void _internal_add_playerids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_playerids();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 playerids(int index) const;
  void set_playerids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_playerids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      playerids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_playerids();

  // @@protoc_insertion_point(class_scope:Protocol.S_PLAYER_EXIT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > playerids_;
  mutable std::atomic<int> _playerids_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_PLAYER_INPUT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_PLAYER_INPUT) */ {
 public:
  inline C_PLAYER_INPUT() : C_PLAYER_INPUT(nullptr) {}
  ~C_PLAYER_INPUT() override;
  explicit constexpr C_PLAYER_INPUT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_PLAYER_INPUT(const C_PLAYER_INPUT& from);
  C_PLAYER_INPUT(C_PLAYER_INPUT&& from) noexcept
    : C_PLAYER_INPUT() {
    *this = ::std::move(from);
  }

  inline C_PLAYER_INPUT& operator=(const C_PLAYER_INPUT& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_PLAYER_INPUT& operator=(C_PLAYER_INPUT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_PLAYER_INPUT& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_PLAYER_INPUT* internal_default_instance() {
    return reinterpret_cast<const C_PLAYER_INPUT*>(
               &_C_PLAYER_INPUT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C_PLAYER_INPUT& a, C_PLAYER_INPUT& b) {
    a.Swap(&b);
  }
  inline void Swap(C_PLAYER_INPUT* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_PLAYER_INPUT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_PLAYER_INPUT* New() const final {
    return new C_PLAYER_INPUT();
  }

  C_PLAYER_INPUT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_PLAYER_INPUT>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_PLAYER_INPUT& from);
  void MergeFrom(const C_PLAYER_INPUT& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_PLAYER_INPUT* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_PLAYER_INPUT";
  }
  protected:
  explicit C_PLAYER_INPUT(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputsFieldNumber = 1,
  };
  // repeated .Protocol.Input inputs = 1;
  int inputs_size() const;
  private:
  int _internal_inputs_size() const;
  public:
  void clear_inputs();
  ::Protocol::Input* mutable_inputs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Input >*
      mutable_inputs();
  private:
  const ::Protocol::Input& _internal_inputs(int index) const;
  ::Protocol::Input* _internal_add_inputs();
  public:
  const ::Protocol::Input& inputs(int index) const;
  ::Protocol::Input* add_inputs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Input >&
      inputs() const;

  // @@protoc_insertion_point(class_scope:Protocol.C_PLAYER_INPUT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Input > inputs_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_PLAYER_MOVE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_PLAYER_MOVE) */ {
 public:
  inline S_PLAYER_MOVE() : S_PLAYER_MOVE(nullptr) {}
  ~S_PLAYER_MOVE() override;
  explicit constexpr S_PLAYER_MOVE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_PLAYER_MOVE(const S_PLAYER_MOVE& from);
  S_PLAYER_MOVE(S_PLAYER_MOVE&& from) noexcept
    : S_PLAYER_MOVE() {
    *this = ::std::move(from);
  }

  inline S_PLAYER_MOVE& operator=(const S_PLAYER_MOVE& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_PLAYER_MOVE& operator=(S_PLAYER_MOVE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_PLAYER_MOVE& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_PLAYER_MOVE* internal_default_instance() {
    return reinterpret_cast<const S_PLAYER_MOVE*>(
               &_S_PLAYER_MOVE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S_PLAYER_MOVE& a, S_PLAYER_MOVE& b) {
    a.Swap(&b);
  }
  inline void Swap(S_PLAYER_MOVE* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_PLAYER_MOVE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_PLAYER_MOVE* New() const final {
    return new S_PLAYER_MOVE();
  }

  S_PLAYER_MOVE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_PLAYER_MOVE>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_PLAYER_MOVE& from);
  void MergeFrom(const S_PLAYER_MOVE& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_PLAYER_MOVE* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_PLAYER_MOVE";
  }
  protected:
  explicit S_PLAYER_MOVE(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformsFieldNumber = 1,
  };
  // repeated .Protocol.TransformData transforms = 1;
  int transforms_size() const;
  private:
  int _internal_transforms_size() const;
  public:
  void clear_transforms();
  ::Protocol::TransformData* mutable_transforms(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >*
      mutable_transforms();
  private:
  const ::Protocol::TransformData& _internal_transforms(int index) const;
  ::Protocol::TransformData* _internal_add_transforms();
  public:
  const ::Protocol::TransformData& transforms(int index) const;
  ::Protocol::TransformData* add_transforms();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >&
      transforms() const;

  // @@protoc_insertion_point(class_scope:Protocol.S_PLAYER_MOVE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData > transforms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_MONSTER_SPAWN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_MONSTER_SPAWN) */ {
 public:
  inline S_MONSTER_SPAWN() : S_MONSTER_SPAWN(nullptr) {}
  ~S_MONSTER_SPAWN() override;
  explicit constexpr S_MONSTER_SPAWN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_MONSTER_SPAWN(const S_MONSTER_SPAWN& from);
  S_MONSTER_SPAWN(S_MONSTER_SPAWN&& from) noexcept
    : S_MONSTER_SPAWN() {
    *this = ::std::move(from);
  }

  inline S_MONSTER_SPAWN& operator=(const S_MONSTER_SPAWN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_MONSTER_SPAWN& operator=(S_MONSTER_SPAWN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_MONSTER_SPAWN& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_MONSTER_SPAWN* internal_default_instance() {
    return reinterpret_cast<const S_MONSTER_SPAWN*>(
               &_S_MONSTER_SPAWN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(S_MONSTER_SPAWN& a, S_MONSTER_SPAWN& b) {
    a.Swap(&b);
  }
  inline void Swap(S_MONSTER_SPAWN* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_MONSTER_SPAWN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_MONSTER_SPAWN* New() const final {
    return new S_MONSTER_SPAWN();
  }

  S_MONSTER_SPAWN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_MONSTER_SPAWN>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_MONSTER_SPAWN& from);
  void MergeFrom(const S_MONSTER_SPAWN& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_MONSTER_SPAWN* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_MONSTER_SPAWN";
  }
  protected:
  explicit S_MONSTER_SPAWN(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMonstersFieldNumber = 1,
  };
  // repeated .Protocol.Monster monsters = 1;
  int monsters_size() const;
  private:
  int _internal_monsters_size() const;
  public:
  void clear_monsters();
  ::Protocol::Monster* mutable_monsters(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Monster >*
      mutable_monsters();
  private:
  const ::Protocol::Monster& _internal_monsters(int index) const;
  ::Protocol::Monster* _internal_add_monsters();
  public:
  const ::Protocol::Monster& monsters(int index) const;
  ::Protocol::Monster* add_monsters();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Monster >&
      monsters() const;

  // @@protoc_insertion_point(class_scope:Protocol.S_MONSTER_SPAWN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Monster > monsters_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_MONSTER_MOVE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_MONSTER_MOVE) */ {
 public:
  inline S_MONSTER_MOVE() : S_MONSTER_MOVE(nullptr) {}
  ~S_MONSTER_MOVE() override;
  explicit constexpr S_MONSTER_MOVE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_MONSTER_MOVE(const S_MONSTER_MOVE& from);
  S_MONSTER_MOVE(S_MONSTER_MOVE&& from) noexcept
    : S_MONSTER_MOVE() {
    *this = ::std::move(from);
  }

  inline S_MONSTER_MOVE& operator=(const S_MONSTER_MOVE& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_MONSTER_MOVE& operator=(S_MONSTER_MOVE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_MONSTER_MOVE& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_MONSTER_MOVE* internal_default_instance() {
    return reinterpret_cast<const S_MONSTER_MOVE*>(
               &_S_MONSTER_MOVE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(S_MONSTER_MOVE& a, S_MONSTER_MOVE& b) {
    a.Swap(&b);
  }
  inline void Swap(S_MONSTER_MOVE* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_MONSTER_MOVE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_MONSTER_MOVE* New() const final {
    return new S_MONSTER_MOVE();
  }

  S_MONSTER_MOVE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_MONSTER_MOVE>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_MONSTER_MOVE& from);
  void MergeFrom(const S_MONSTER_MOVE& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_MONSTER_MOVE* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_MONSTER_MOVE";
  }
  protected:
  explicit S_MONSTER_MOVE(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformsFieldNumber = 1,
  };
  // repeated .Protocol.TransformData transforms = 1;
  int transforms_size() const;
  private:
  int _internal_transforms_size() const;
  public:
  void clear_transforms();
  ::Protocol::TransformData* mutable_transforms(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >*
      mutable_transforms();
  private:
  const ::Protocol::TransformData& _internal_transforms(int index) const;
  ::Protocol::TransformData* _internal_add_transforms();
  public:
  const ::Protocol::TransformData& transforms(int index) const;
  ::Protocol::TransformData* add_transforms();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >&
      transforms() const;

  // @@protoc_insertion_point(class_scope:Protocol.S_MONSTER_MOVE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData > transforms_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_MONSTER_DESPAWN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_MONSTER_DESPAWN) */ {
 public:
  inline S_MONSTER_DESPAWN() : S_MONSTER_DESPAWN(nullptr) {}
  ~S_MONSTER_DESPAWN() override;
  explicit constexpr S_MONSTER_DESPAWN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_MONSTER_DESPAWN(const S_MONSTER_DESPAWN& from);
  S_MONSTER_DESPAWN(S_MONSTER_DESPAWN&& from) noexcept
    : S_MONSTER_DESPAWN() {
    *this = ::std::move(from);
  }

  inline S_MONSTER_DESPAWN& operator=(const S_MONSTER_DESPAWN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_MONSTER_DESPAWN& operator=(S_MONSTER_DESPAWN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_MONSTER_DESPAWN& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_MONSTER_DESPAWN* internal_default_instance() {
    return reinterpret_cast<const S_MONSTER_DESPAWN*>(
               &_S_MONSTER_DESPAWN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(S_MONSTER_DESPAWN& a, S_MONSTER_DESPAWN& b) {
    a.Swap(&b);
  }
  inline void Swap(S_MONSTER_DESPAWN* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_MONSTER_DESPAWN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_MONSTER_DESPAWN* New() const final {
    return new S_MONSTER_DESPAWN();
  }

  S_MONSTER_DESPAWN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_MONSTER_DESPAWN>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_MONSTER_DESPAWN& from);
  void MergeFrom(const S_MONSTER_DESPAWN& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_MONSTER_DESPAWN* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_MONSTER_DESPAWN";
  }
  protected:
  explicit S_MONSTER_DESPAWN(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMonsterIdsFieldNumber = 1,
  };
  // repeated uint64 monsterIds = 1;
  int monsterids_size() const;
  private:
  int _internal_monsterids_size() const;
  public:
  void clear_monsterids();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_monsterids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_monsterids() const;
  void _internal_add_monsterids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_monsterids();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 monsterids(int index) const;
  void set_monsterids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_monsterids(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      monsterids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_monsterids();

  // @@protoc_insertion_point(class_scope:Protocol.S_MONSTER_DESPAWN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > monsterids_;
  mutable std::atomic<int> _monsterids_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_CHAT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_CHAT) */ {
 public:
  inline C_CHAT() : C_CHAT(nullptr) {}
  ~C_CHAT() override;
  explicit constexpr C_CHAT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_CHAT(const C_CHAT& from);
  C_CHAT(C_CHAT&& from) noexcept
    : C_CHAT() {
    *this = ::std::move(from);
  }

  inline C_CHAT& operator=(const C_CHAT& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_CHAT& operator=(C_CHAT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_CHAT& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_CHAT* internal_default_instance() {
    return reinterpret_cast<const C_CHAT*>(
               &_C_CHAT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(C_CHAT& a, C_CHAT& b) {
    a.Swap(&b);
  }
  inline void Swap(C_CHAT* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_CHAT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_CHAT* New() const final {
    return new C_CHAT();
  }

  C_CHAT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_CHAT>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_CHAT& from);
  void MergeFrom(const C_CHAT& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_CHAT* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_CHAT";
  }
  protected:
  explicit C_CHAT(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 1,
  };
  // string msg = 1;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_CHAT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_CHAT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_CHAT) */ {
 public:
  inline S_CHAT() : S_CHAT(nullptr) {}
  ~S_CHAT() override;
  explicit constexpr S_CHAT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_CHAT(const S_CHAT& from);
  S_CHAT(S_CHAT&& from) noexcept
    : S_CHAT() {
    *this = ::std::move(from);
  }

  inline S_CHAT& operator=(const S_CHAT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_CHAT& operator=(S_CHAT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_CHAT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_CHAT* internal_default_instance() {
    return reinterpret_cast<const S_CHAT*>(
               &_S_CHAT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  friend void swap(S_CHAT& a, S_CHAT& b) {
    a.Swap(&b);
  }
  inline void Swap(S_CHAT* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_CHAT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_CHAT* New() const final {
    return new S_CHAT();
  }

  S_CHAT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_CHAT>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_CHAT& from);
  void MergeFrom(const S_CHAT& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_CHAT* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_CHAT";
  }
  protected:
  explicit S_CHAT(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
  };
  // string msg = 2;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // uint64 playerId = 1;
  void clear_playerid();
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid() const;
  void set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_playerid() const;
  void _internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_CHAT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  ::PROTOBUF_NAMESPACE_ID::uint64 playerid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_LOGIN

// string name = 1;
inline void C_LOGIN::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& C_LOGIN::name() const {
  // @@protoc_insertion_point(field_get:Protocol.C_LOGIN.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_LOGIN::set_name(ArgT0&& arg0, ArgT... args) {
 
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_LOGIN.name)
}
inline std::string* C_LOGIN::mutable_name() {
  // @@protoc_insertion_point(field_mutable:Protocol.C_LOGIN.name)
  return _internal_mutable_name();
}
inline const std::string& C_LOGIN::_internal_name() const {
  return name_.Get();
}
inline void C_LOGIN::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* C_LOGIN::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* C_LOGIN::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.C_LOGIN.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void C_LOGIN::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LOGIN.name)
}

// -------------------------------------------------------------------

// S_LOGIN

// bool success = 1;
inline void S_LOGIN::clear_success() {
  success_ = false;
}
inline bool S_LOGIN::_internal_success() const {
  return success_;
}
inline bool S_LOGIN::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.success)
  return _internal_success();
}
inline void S_LOGIN::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void S_LOGIN::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.success)
}

// .Protocol.Player myPlayer = 2;
inline bool S_LOGIN::_internal_has_myplayer() const {
  return this != internal_default_instance() && myplayer_ != nullptr;
}
inline bool S_LOGIN::has_myplayer() const {
  return _internal_has_myplayer();
}
inline const ::Protocol::Player& S_LOGIN::_internal_myplayer() const {
  const ::Protocol::Player* p = myplayer_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Player&>(
      ::Protocol::_Player_default_instance_);
}
inline const ::Protocol::Player& S_LOGIN::myplayer() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.myPlayer)
  return _internal_myplayer();
}
inline void S_LOGIN::unsafe_arena_set_allocated_myplayer(
    ::Protocol::Player* myplayer) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(myplayer_);
  }
  myplayer_ = myplayer;
  if (myplayer) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S_LOGIN.myPlayer)
}
inline ::Protocol::Player* S_LOGIN::release_myplayer() {
  
  ::Protocol::Player* temp = myplayer_;
  myplayer_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Protocol::Player* S_LOGIN::unsafe_arena_release_myplayer() {
  // @@protoc_insertion_point(field_release:Protocol.S_LOGIN.myPlayer)
  
  ::Protocol::Player* temp = myplayer_;
  myplayer_ = nullptr;
  return temp;
}
inline ::Protocol::Player* S_LOGIN::_internal_mutable_myplayer() {
  
  if (myplayer_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Player>(GetArenaForAllocation());
    myplayer_ = p;
  }
  return myplayer_;
}
inline ::Protocol::Player* S_LOGIN::mutable_myplayer() {
  // @@protoc_insertion_point(field_mutable:Protocol.S_LOGIN.myPlayer)
  return _internal_mutable_myplayer();
}
inline void S_LOGIN::set_allocated_myplayer(::Protocol::Player* myplayer) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(myplayer_);
  }
  if (myplayer) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(myplayer));
    if (message_arena != submessage_arena) {
      myplayer = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, myplayer, submessage_arena);
    }
    
  } else {
    
  }
  myplayer_ = myplayer;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_LOGIN.myPlayer)
}

// repeated .Protocol.Player otherPlayers = 3;
inline int S_LOGIN::_internal_otherplayers_size() const {
  return otherplayers_.size();
}
inline int S_LOGIN::otherplayers_size() const {
  return _internal_otherplayers_size();
}
inline ::Protocol::Player* S_LOGIN::mutable_otherplayers(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_LOGIN.otherPlayers)
  return otherplayers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
S_LOGIN::mutable_otherplayers() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_LOGIN.otherPlayers)
  return &otherplayers_;
}
inline const ::Protocol::Player& S_LOGIN::_internal_otherplayers(int index) const {
  return otherplayers_.Get(index);
}
inline const ::Protocol::Player& S_LOGIN::otherplayers(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.otherPlayers)
  return _internal_otherplayers(index);
}
inline ::Protocol::Player* S_LOGIN::_internal_add_otherplayers() {
  return otherplayers_.Add();
}
inline ::Protocol::Player* S_LOGIN::add_otherplayers() {
  // @@protoc_insertion_point(field_add:Protocol.S_LOGIN.otherPlayers)
  return _internal_add_otherplayers();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
S_LOGIN::otherplayers() const {
  // @@protoc_insertion_point(field_list:Protocol.S_LOGIN.otherPlayers)
  return otherplayers_;
}

// -------------------------------------------------------------------

// S_PLAYER_ENTER

// repeated .Protocol.Player players = 1;
inline int S_PLAYER_ENTER::_internal_players_size() const {
  return players_.size();
}
inline int S_PLAYER_ENTER::players_size() const {
  return _internal_players_size();
}
inline ::Protocol::Player* S_PLAYER_ENTER::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_ENTER.players)
  return players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >*
S_PLAYER_ENTER::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_PLAYER_ENTER.players)
  return &players_;
}
inline const ::Protocol::Player& S_PLAYER_ENTER::_internal_players(int index) const {
  return players_.Get(index);
}
inline const ::Protocol::Player& S_PLAYER_ENTER::players(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_ENTER.players)
  return _internal_players(index);
}
inline ::Protocol::Player* S_PLAYER_ENTER::_internal_add_players() {
  return players_.Add();
}
inline ::Protocol::Player* S_PLAYER_ENTER::add_players() {
  // @@protoc_insertion_point(field_add:Protocol.S_PLAYER_ENTER.players)
  return _internal_add_players();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Player >&
S_PLAYER_ENTER::players() const {
  // @@protoc_insertion_point(field_list:Protocol.S_PLAYER_ENTER.players)
  return players_;
}

// -------------------------------------------------------------------

// S_PLAYER_EXIT

// repeated uint64 playerIds = 1;
inline int S_PLAYER_EXIT::_internal_playerids_size() const {
  return playerids_.size();
}
inline int S_PLAYER_EXIT::playerids_size() const {
  return _internal_playerids_size();
}
inline void S_PLAYER_EXIT::clear_playerids() {
  playerids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_PLAYER_EXIT::_internal_playerids(int index) const {
  return playerids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_PLAYER_EXIT::playerids(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_EXIT.playerIds)
  return _internal_playerids(index);
}
inline void S_PLAYER_EXIT::set_playerids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  playerids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_PLAYER_EXIT.playerIds)
}
inline void S_PLAYER_EXIT::_internal_add_playerids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  playerids_.Add(value);
}
inline void S_PLAYER_EXIT::add_playerids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_playerids(value);
  // @@protoc_insertion_point(field_add:Protocol.S_PLAYER_EXIT.playerIds)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
S_PLAYER_EXIT::_internal_playerids() const {
  return playerids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
S_PLAYER_EXIT::playerids() const {
  // @@protoc_insertion_point(field_list:Protocol.S_PLAYER_EXIT.playerIds)
  return _internal_playerids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
S_PLAYER_EXIT::_internal_mutable_playerids() {
  return &playerids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
S_PLAYER_EXIT::mutable_playerids() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_PLAYER_EXIT.playerIds)
  return _internal_mutable_playerids();
}

// -------------------------------------------------------------------

// C_PLAYER_INPUT

// repeated .Protocol.Input inputs = 1;
inline int C_PLAYER_INPUT::_internal_inputs_size() const {
  return inputs_.size();
}
inline int C_PLAYER_INPUT::inputs_size() const {
  return _internal_inputs_size();
}
inline ::Protocol::Input* C_PLAYER_INPUT::mutable_inputs(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.C_PLAYER_INPUT.inputs)
  return inputs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Input >*
C_PLAYER_INPUT::mutable_inputs() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.C_PLAYER_INPUT.inputs)
  return &inputs_;
}
inline const ::Protocol::Input& C_PLAYER_INPUT::_internal_inputs(int index) const {
  return inputs_.Get(index);
}
inline const ::Protocol::Input& C_PLAYER_INPUT::inputs(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.C_PLAYER_INPUT.inputs)
  return _internal_inputs(index);
}
inline ::Protocol::Input* C_PLAYER_INPUT::_internal_add_inputs() {
  return inputs_.Add();
}
inline ::Protocol::Input* C_PLAYER_INPUT::add_inputs() {
  // @@protoc_insertion_point(field_add:Protocol.C_PLAYER_INPUT.inputs)
  return _internal_add_inputs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Input >&
C_PLAYER_INPUT::inputs() const {
  // @@protoc_insertion_point(field_list:Protocol.C_PLAYER_INPUT.inputs)
  return inputs_;
}

// -------------------------------------------------------------------

// S_PLAYER_MOVE

// repeated .Protocol.TransformData transforms = 1;
inline int S_PLAYER_MOVE::_internal_transforms_size() const {
  return transforms_.size();
}
inline int S_PLAYER_MOVE::transforms_size() const {
  return _internal_transforms_size();
}
inline ::Protocol::TransformData* S_PLAYER_MOVE::mutable_transforms(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_PLAYER_MOVE.transforms)
  return transforms_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >*
S_PLAYER_MOVE::mutable_transforms() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_PLAYER_MOVE.transforms)
  return &transforms_;
}
inline const ::Protocol::TransformData& S_PLAYER_MOVE::_internal_transforms(int index) const {
  return transforms_.Get(index);
}
inline const ::Protocol::TransformData& S_PLAYER_MOVE::transforms(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_PLAYER_MOVE.transforms)
  return _internal_transforms(index);
}
inline ::Protocol::TransformData* S_PLAYER_MOVE::_internal_add_transforms() {
  return transforms_.Add();
}
inline ::Protocol::TransformData* S_PLAYER_MOVE::add_transforms() {
  // @@protoc_insertion_point(field_add:Protocol.S_PLAYER_MOVE.transforms)
  return _internal_add_transforms();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >&
S_PLAYER_MOVE::transforms() const {
  // @@protoc_insertion_point(field_list:Protocol.S_PLAYER_MOVE.transforms)
  return transforms_;
}

// -------------------------------------------------------------------

// S_MONSTER_SPAWN

// repeated .Protocol.Monster monsters = 1;
inline int S_MONSTER_SPAWN::_internal_monsters_size() const {
  return monsters_.size();
}
inline int S_MONSTER_SPAWN::monsters_size() const {
  return _internal_monsters_size();
}
inline ::Protocol::Monster* S_MONSTER_SPAWN::mutable_monsters(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_MONSTER_SPAWN.monsters)
  return monsters_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Monster >*
S_MONSTER_SPAWN::mutable_monsters() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_MONSTER_SPAWN.monsters)
  return &monsters_;
}
inline const ::Protocol::Monster& S_MONSTER_SPAWN::_internal_monsters(int index) const {
  return monsters_.Get(index);
}
inline const ::Protocol::Monster& S_MONSTER_SPAWN::monsters(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_MONSTER_SPAWN.monsters)
  return _internal_monsters(index);
}
inline ::Protocol::Monster* S_MONSTER_SPAWN::_internal_add_monsters() {
  return monsters_.Add();
}
inline ::Protocol::Monster* S_MONSTER_SPAWN::add_monsters() {
  // @@protoc_insertion_point(field_add:Protocol.S_MONSTER_SPAWN.monsters)
  return _internal_add_monsters();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Monster >&
S_MONSTER_SPAWN::monsters() const {
  // @@protoc_insertion_point(field_list:Protocol.S_MONSTER_SPAWN.monsters)
  return monsters_;
}

// -------------------------------------------------------------------

// S_MONSTER_MOVE

// repeated .Protocol.TransformData transforms = 1;
inline int S_MONSTER_MOVE::_internal_transforms_size() const {
  return transforms_.size();
}
inline int S_MONSTER_MOVE::transforms_size() const {
  return _internal_transforms_size();
}
inline ::Protocol::TransformData* S_MONSTER_MOVE::mutable_transforms(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S_MONSTER_MOVE.transforms)
  return transforms_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >*
S_MONSTER_MOVE::mutable_transforms() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_MONSTER_MOVE.transforms)
  return &transforms_;
}
inline const ::Protocol::TransformData& S_MONSTER_MOVE::_internal_transforms(int index) const {
  return transforms_.Get(index);
}
inline const ::Protocol::TransformData& S_MONSTER_MOVE::transforms(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_MONSTER_MOVE.transforms)
  return _internal_transforms(index);
}
inline ::Protocol::TransformData* S_MONSTER_MOVE::_internal_add_transforms() {
  return transforms_.Add();
}
inline ::Protocol::TransformData* S_MONSTER_MOVE::add_transforms() {
  // @@protoc_insertion_point(field_add:Protocol.S_MONSTER_MOVE.transforms)
  return _internal_add_transforms();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::TransformData >&
S_MONSTER_MOVE::transforms() const {
  // @@protoc_insertion_point(field_list:Protocol.S_MONSTER_MOVE.transforms)
  return transforms_;
}

// -------------------------------------------------------------------

// S_MONSTER_DESPAWN

// repeated uint64 monsterIds = 1;
inline int S_MONSTER_DESPAWN::_internal_monsterids_size() const {
  return monsterids_.size();
}
inline int S_MONSTER_DESPAWN::monsterids_size() const {
  return _internal_monsterids_size();
}
inline void S_MONSTER_DESPAWN::clear_monsterids() {
  monsterids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_MONSTER_DESPAWN::_internal_monsterids(int index) const {
  return monsterids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_MONSTER_DESPAWN::monsterids(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S_MONSTER_DESPAWN.monsterIds)
  return _internal_monsterids(index);
}
inline void S_MONSTER_DESPAWN::set_monsterids(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  monsterids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S_MONSTER_DESPAWN.monsterIds)
}
inline void S_MONSTER_DESPAWN::_internal_add_monsterids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  monsterids_.Add(value);
}
inline void S_MONSTER_DESPAWN::add_monsterids(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_monsterids(value);
  // @@protoc_insertion_point(field_add:Protocol.S_MONSTER_DESPAWN.monsterIds)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
S_MONSTER_DESPAWN::_internal_monsterids() const {
  return monsterids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
S_MONSTER_DESPAWN::monsterids() const {
  // @@protoc_insertion_point(field_list:Protocol.S_MONSTER_DESPAWN.monsterIds)
  return _internal_monsterids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
S_MONSTER_DESPAWN::_internal_mutable_monsterids() {
  return &monsterids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
S_MONSTER_DESPAWN::mutable_monsterids() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_MONSTER_DESPAWN.monsterIds)
  return _internal_mutable_monsterids();
}

// -------------------------------------------------------------------

// C_CHAT

// string msg = 1;
inline void C_CHAT::clear_msg() {
  msg_.ClearToEmpty();
}
inline const std::string& C_CHAT::msg() const {
  // @@protoc_insertion_point(field_get:Protocol.C_CHAT.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_CHAT::set_msg(ArgT0&& arg0, ArgT... args) {
 
 msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_CHAT.msg)
}
inline std::string* C_CHAT::mutable_msg() {
  // @@protoc_insertion_point(field_mutable:Protocol.C_CHAT.msg)
  return _internal_mutable_msg();
}
inline const std::string& C_CHAT::_internal_msg() const {
  return msg_.Get();
}
inline void C_CHAT::_internal_set_msg(const std::string& value) {
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* C_CHAT::_internal_mutable_msg() {
  
  return msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* C_CHAT::release_msg() {
  // @@protoc_insertion_point(field_release:Protocol.C_CHAT.msg)
  return msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void C_CHAT::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_CHAT.msg)
}

// -------------------------------------------------------------------

// S_CHAT

// uint64 playerId = 1;
inline void S_CHAT::clear_playerid() {
  playerid_ = uint64_t{0u};
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_CHAT::_internal_playerid() const {
  return playerid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 S_CHAT::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_CHAT.playerId)
  return _internal_playerid();
}
inline void S_CHAT::_internal_set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  playerid_ = value;
}
inline void S_CHAT::set_playerid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_CHAT.playerId)
}

// string msg = 2;
inline void S_CHAT::clear_msg() {
  msg_.ClearToEmpty();
}
inline const std::string& S_CHAT::msg() const {
  // @@protoc_insertion_point(field_get:Protocol.S_CHAT.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S_CHAT::set_msg(ArgT0&& arg0, ArgT... args) {
 
 msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.S_CHAT.msg)
}
inline std::string* S_CHAT::mutable_msg() {
  // @@protoc_insertion_point(field_mutable:Protocol.S_CHAT.msg)
  return _internal_mutable_msg();
}
inline const std::string& S_CHAT::_internal_msg() const {
  return msg_.Get();
}
inline void S_CHAT::_internal_set_msg(const std::string& value) {
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* S_CHAT::_internal_mutable_msg() {
  
  return msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* S_CHAT::release_msg() {
  // @@protoc_insertion_point(field_release:Protocol.S_CHAT.msg)
  return msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void S_CHAT::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_CHAT.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
